name: Documentation

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
              python-version: 3.8
      - name: Install graphviz
        run: sudo apt install graphviz
        shell: bash 
      - name: Install dependencies
        run: |
              sudo pip3 install --upgrade pip
              sudo pip3 install sphinx_rtd_theme
              sudo pip3 install sphinx==2.2.0
              sudo pip3 install pytest
              sudo pip3 install pytest-check            
      - name: Execute py script
        env:
              working-directory: ${{runner.workspace}}/cimpy
      #- name: build-documentation
      #  uses: ./

      - name: Create doc redirect
        uses: "finnp/create-file-action@master"
        env:
            FILE_NAME: ${{ github.workspace }}/built_documentation/.nojekyll
            FILE_DATA: ""

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ${{ github.workspace }}/built_documentation
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to get a token
          MESSAGE: "Build documentation: ({sha}) {msg}"
